### ISSUE TITLE
Admin unable to see new joins in their dashboard.

### ISSUE THREAD

**Issue by thapaaashish** [sarthak2331183/HRMS-PROJECT#12] opened 2024-05-20 03:54 UTC
Admins are unable to see new joins in their dashboard. The list of new members is not updated, which leads to missing information regarding the recent users who have joined.

Expected Behavior:
New joins should be displayed correctly in the admin dashboard.

Actual Behavior:
New joins are not displayed in the admin dashboard.

![image](https://github.com/sarthak2331183/HRMS-PROJECT/assets/119116507/57109bab-00f0-4b03-9c27-fa03776cc564)

**Comment by sarthak2331183** [comment] 2024-05-20 06:09
This issue seems to be impacting the visibility of new joins in the admin dashboard, leading to potential gaps in user information. As a next step, we should do backend the root cause of this issue and prioritize implementing a solution to ensure that new joins are accurately displayed as expected in the admin dashboard.

**Comment by ShrijanThapa77** [comment] 2024-05-28 12:28
the issue is now fixed .

**Closed as completed** 2024-05-29 01:45 UTC
Labels: bug, enhancement, help wanted
